name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk@2
      
      - name: Install ts-node (if needed)
        run: npm install -g ts-node

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Install dependencies
        run: npm install
        working-directory: my-react-app

      - name: Build the React app
        run: npm run build
        working-directory: my-react-app

      # Add destroy step to delete existing resources
      - name: Destroy existing resources
        run: cdk destroy --force
        continue-on-error: true
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      # Build and deploy CDK stack after destroying existing resources
      - name: Build and deploy CDK stack
        run: cdk deploy --require-approval never
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      # - name: Build and deploy CDK stack
      #   run: |
      #     cdk bootstrap --require-approval never
      #     cdk deploy --require-approval never
      #   env:
      #     NODE_OPTIONS: --max-old-space-size=4096
