name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the directory
        run: ls -al

      # - name: Change directory to the CDK project
      #   run: cd setup

      - name: List files in the CDK project directory
        run: ls -al

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: npm install

      - name: Build and deploy CDK stack
        run: cdk deploy --require-approval never --app 'node bin/setup.js'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
